ARG ANSIBLE_BASE_IMAGE=iyorozuya/ansible:base-python39
FROM $ANSIBLE_BASE_IMAGE
LABEL maintainer="iyorozuya"

# Args
ARG USERNAME=alma
ARG ANSIBLE_CORE_VERSION

# Install ansible-core
USER $USERNAME
RUN pip3 install --user ansible-core==${ANSIBLE_CORE_VERSION}.*

WORKDIR /app

CMD ["tail", "-f", "/dev/null"]
