FROM iyorozuya/ansible:base
LABEL maintainer="iyorozuya"

# Args
ARG USERNAME=alma
ARG ANSIBLE_VERSION

# Install ansible
USER $USERNAME
RUN pip3 install --user ansible==${ANSIBLE_VERSION}

WORKDIR /app

CMD ["tail", "-f", "/dev/null"]
