ARG ANSIBLE_BASE_IMAGE=iyorozuya/ansible:base-python39
FROM $ANSIBLE_BASE_IMAGE
LABEL maintainer="iyorozuya"

# Args
ARG USERNAME=alma
ARG ANSIBLE_VERSION

# Install sshd
RUN dnf install openssh-server openssh-clients -y
RUN systemctl enable sshd

# Install ansible
USER $USERNAME
RUN pip3 install --user ansible==${ANSIBLE_VERSION}.*

WORKDIR /app

CMD ["ansible"]
